import pandas as pd
Device=[
    {"name": "Intel i5(8th gen)", "type": "0.5", "Manufacturing Year": "2017", "Credit":"10"},
    {"name": "Intel i7(8th gen)", "type": "0.5", "Manufacturing Year": "2017", "Credit":"11"},
    {"name": "Intel i9(8th gen)", "type": "0.5", "Manufacturing Year": "2017", "Credit":"12"},
    {"name": "2080ti", "type": "0.5", "Manufacturing Year": "2018", "Credit":"20"},
    {"name": "3070", "type": "0.5", "Manufacturing Year": "2020", "Credit":"30"},
    {"name": "3080", "type": "0.5", "Manufacturing Year": "2020", "Credit":"35"},
    {"name": "3090", "type": "0.5", "Manufacturing Year": "2020", "Credit":"40"},
    {"name": "4070", "type": "0.5", "Manufacturing Year": "2023", "Credit":"55"},
    {"name": "4090", "type": "0.5", "Manufacturing Year": "2023", "Credit":"65"},
    {"name": "B450 motherboard", "type": "0.5", "Manufacturing Year": "2018", "Credit":"70"},
    {"name": "X470 motherboard", "type": "0.5", "Manufacturing Year": "2018", "Credit":"71"},
    {"name": "A520", "type": "0.5", "Manufacturing Year": "2020", "Credit":"80"},
    {"name": "Ram(single stick)", "type": "0.5", "Manufacturing Year": "2010", "Credit":"1"},
    {"name": "SSD", "type": "0.5", "Manufacturing Year": "2010", "Credit":"8"},
    {"name": "SSD", "type": "0.5", "Manufacturing Year": "2014", "Credit":"13"},
    {"name": "SSD", "type": "0.5", "Manufacturing Year": "2018", "Credit":"15"},
    {"name": "SSD", "type": "0.5", "Manufacturing Year": "2023", "Credit":"23"},
    {"name": "Hard Drives", "type": "0.5", "Manufacturing Year": "2010", "Credit":"5"},
    {"name": "Floppy discs", "type": "0.5", "Manufacturing Year": "2000", "Credit":"8"},
    {"name": "CDs", "type": "0.5", "Manufacturing Year": "2010", "Credit":"18"},
    {"name": "USB Stick", "type": "0.5", "Manufacturing Year": "2015", "Credit":"29"},
    {"name": "Power Supply", "type": "0.5", "Manufacturing Year": "2010", "Credit":"56"},
    {"name": "Wires(per meter)", "type": "0.5", "Manufacturing Year": "2001", "Credit":"3"},
    {"name": "Hair Dyer, trimmer, etc", "type": "0.5", "Manufacturing Year": "2005", "Credit":"44"},
    {"name": "Elctric toothbrush, small toys, etc", "type": "0.5", "Manufacturing Year": "2015", "Credit":"24"},
    {"name": "Mouse, Keyboard)", "type": "0.5", "Manufacturing Year": "2013", "Credit":"34"},
    {"name": "Smart Watch", "type": "0.5", "Manufacturing Year": "2017", "Credit":"38"},
    {"name": "Apple Watch", "type": "0.5", "Manufacturing Year": "2017", "Credit":"42"},
    {"name": "Batteries", "type": "0.5", "Manufacturing Year": "1990", "Credit":"6"},
    {"name": "Blender", "type": "0.5", "Manufacturing Year": "2005", "Credit":"58"},
    {"name": "Blubs, tube lights(non-led)", "type": "0.5", "Manufacturing Year": "1990", "Credit":"12"},
    {"name": "Blubs, tube lights(leds)", "type": "0.5", "Manufacturing Year": "2010", "Credit":"47"},
    
    {"name": "Samsung Duo", "type": "1", "Manufacturing Year": "2012", "Credit":"70"},
    {"name": "Nokia 3310", "type": "1", "Manufacturing Year": "2000", "Credit":"66"},
    {"name": "Blackberry", "type": "1", "Manufacturing Year": "1999", "Credit":"54"},
    {"name": "Iphone", "type": "1", "Manufacturing Year": "2007", "Credit":"100"},
    {"name": "Iphone 10", "type": "1", "Manufacturing Year": "2017", "Credit":"200"},
    {"name": "Iphone 15", "type": "1", "Manufacturing Year": "2023", "Credit":"10000"},
    {"name": "Samsung Galaxy", "type": "1", "Manufacturing Year": "2009", "Credit":"110"},
    {"name": "Samsung Galaxy s23", "type": "1", "Manufacturing Year": "2023", "Credit":"10010"},
    {"name": "Samsung Galaxy m54", "type": "1", "Manufacturing Year": "2019", "Credit":"240"},
    {"name": "Samsung Galaxy m32", "type": "1", "Manufacturing Year": "2019", "Credit":"230"},
    {"name": "Samsung Fold 3", "type": "1", "Manufacturing Year": "2020", "Credit":"300"},
    {"name": "Samsung Flip", "type": "1", "Manufacturing Year": "2022", "Credit":"150"},
    {"name": "One Plus", "type": "1", "Manufacturing Year": "2014", "Credit":"101"},
    {"name": "One Plus 3", "type": "1", "Manufacturing Year": "2016", "Credit":"144"},
    {"name": "One Plus 5", "type": "1", "Manufacturing Year": "2017", "Credit":"170"},
    {"name": "One Plus 7", "type": "1", "Manufacturing Year": "2019", "Credit":"290"},
    {"name": "One Plus 9", "type": "1", "Manufacturing Year": "2021", "Credit":"340"},
    {"name": "Samsung Galaxy Tab A8", "type": "1", "Manufacturing Year": "2022", "Credit":"260"},
    {"name": "Samsung Galsxy Tab A5", "type": "1", "Manufacturing Year": "2017", "Credit":"210"},
    {"name": "Ipad ", "type": "1", "Manufacturing Year": "2021", "Credit":"270"},
    {"name": "Ipad Pro", "type": "1", "Manufacturing Year": "2021", "Credit":"295"},
    {"name": "Ipad mini", "type": "1", "Manufacturing Year": "2021", "Credit":"265"},
    {"name": "Ipad Air", "type": "1", "Manufacturing Year": "2021", "Credit":"268"},
    {"name": "Google Pixel 3", "type": "1", "Manufacturing Year": "2018", "Credit":"235"},
    {"name": "Google Pixel 6", "type": "1", "Manufacturing Year": "2021", "Credit":"305"},
    {"name": "Xiaomi 12S", "type": "1", "Manufacturing Year": "2022", "Credit":"365"},
    {"name": "Xiaomi 10S", "type": "1", "Manufacturing Year": "2020", "Credit":"285"},
    {"name": "Ipod Shuffle", "type": "1", "Manufacturing Year": "2005", "Credit":"74"},
    {"name": "Ipod touch", "type": "1", "Manufacturing Year": "2012", "Credit":"100"},
    {"name": "Walkman(Cassete Player)", "type": "1", "Manufacturing Year": "1979", "Credit":"68"},
    {"name": "Walkman", "type": "1", "Manufacturing Year": "2022", "Credit":"1008"},
    {"name": "Telephones, landlines, etc", "type": "1", "Manufacturing Year": "1990", "Credit":"330"},

    {"name": "Radios", "type": "2", "Manufacturing Year": "2000", "Credit":"2000"},#depends on size
    {"name": "Cassete Players", "type": "2", "Manufacturing Year": "1990", "Credit":"400"},#depends on size
    {"name": "Boombox", "type": "2", "Manufacturing Year": "1990", "Credit":"365"},#depends on size
    {"name": "Cassete Players", "type": "2", "Manufacturing Year": "1990", "Credit":"232"},#depends on the size
    {"name": "Old Speakers", "type": "2", "Manufacturing Year": "1990", "Credit":"450"},#depends on the size
    {"name": "Microphones", "type": "2", "Manufacturing Year": "1990", "Credit":"127"},

    {"name": "Apple MacBook Air", "type": "2.5", "Manufacturing Year": "2018", "Credit": "800"},
    {"name": "Dell XPS 13", "type": "2.5", "Manufacturing Year": "2019", "Credit": "780"},
    {"name": "Lenovo ThinkPad X1 Carbon", "type": "2.5", "Manufacturing Year": "2017", "Credit": "790"},
    {"name": "HP Spectre x360", "type": "2.5", "Manufacturing Year": "2020", "Credit": "770"},
    {"name": "Microsoft Surface Laptop", "type": "2.5", "Manufacturing Year": "2019", "Credit": "780"},
    {"name": "Asus ZenBook", "type": "2.5", "Manufacturing Year": "2021", "Credit": "760"},
    {"name": "Acer Swift 3", "type": "2.5", "Manufacturing Year": "2020", "Credit": "770"},
    {"name": "LG Gram", "type": "2.5", "Manufacturing Year": "2018", "Credit": "800"},
    {"name": "Razer Blade", "type": "2.5", "Manufacturing Year": "2022", "Credit": "730"},
    {"name": "MSI GS66 Stealth", "type": "2.5", "Manufacturing Year": "2021", "Credit": "760"},
    {"name": "Google Pixelbook", "type": "2.5", "Manufacturing Year": "2017", "Credit": "790"},
    {"name": "Huawei MateBook X Pro", "type": "2.5", "Manufacturing Year": "2018", "Credit": "800"},
    {"name": "Samsung Galaxy Book", "type": "2.5", "Manufacturing Year": "2019", "Credit": "780"},
    {"name": "LG Gram 17", "type": "2.5", "Manufacturing Year": "2020", "Credit": "770"},
    {"name": "Lenovo Yoga C930", "type": "2.5", "Manufacturing Year": "2019", "Credit": "780"},
    {"name": "Dell Inspiron", "type": "2.5", "Manufacturing Year": "2022", "Credit": "730"},
    {"name": "HP Envy x360", "type": "2.5", "Manufacturing Year": "2021", "Credit": "760"},
    {"name": "Acer Predator Helios", "type": "2.5", "Manufacturing Year": "2018", "Credit": "800"},
    {"name": "Asus ROG Zephyrus", "type": "2.5", "Manufacturing Year": "2023", "Credit": "400"},
    {"name": "MSI Prestige", "type": "2.5", "Manufacturing Year": "2022", "Credit": "730"},
    {"name": "Lenovo Legion", "type": "2.5", "Manufacturing Year": "2020", "Credit": "770"},
    {"name": "Razer Blade Stealth", "type": "2.5", "Manufacturing Year": "2021", "Credit": "760"},
    {"name": "Dell Precision", "type": "2.5", "Manufacturing Year": "2019", "Credit": "780"},
    {"name": "Apple MacBook Pro", "type": "2.5", "Manufacturing Year": "2022", "Credit": "730"},
    {"name": "Microsoft Surface Book", "type": "2.5", "Manufacturing Year": "2020", "Credit": "770"},
    {"name": "HP Pavilion", "type": "2.5", "Manufacturing Year": "2021", "Credit": "760"},
    {"name": "Acer Aspire", "type": "2.5", "Manufacturing Year": "2018", "Credit": "800"},
    {"name": "Asus VivoBook", "type": "2.5", "Manufacturing Year": "2019", "Credit": "780"},
    {"name": "LG Gram 14", "type": "2.5", "Manufacturing Year": "2020", "Credit": "770"},
    {"name": "Lenovo IdeaPad", "type": "2.5", "Manufacturing Year": "2017", "Credit": "790"},
    {"name": "Dell Latitude", "type": "2.5", "Manufacturing Year": "2018", "Credit": "800"},
    {"name": "Microsoft Surface Pro", "type": "2.5", "Manufacturing Year": "2019", "Credit": "780"},
    {"name": "HP EliteBook", "type": "2.5", "Manufacturing Year": "2022", "Credit": "730"},
    {"name": "Acer Chromebook", "type": "2.5", "Manufacturing Year": "2021", "Credit": "760"},
    {"name": "Asus TUF Gaming", "type": "2.5", "Manufacturing Year": "2020", "Credit": "770"},
    {"name": "MSI GE75 Raider", "type": "2.5", "Manufacturing Year": "2023", "Credit": "400"},
    {"name": "Lenovo Chromebook", "type": "2.5", "Manufacturing Year": "2022", "Credit": "730"},
    {"name": "Dell Vostro", "type": "2.5", "Manufacturing Year": "2020", "Credit": "770"},
    {"name": "HP Omen", "type": "2.5", "Manufacturing Year": "2021", "Credit": "760"},

    {"name": "Samsung 27-inch 4K Monitor", "type": "3", "Manufacturing Year": "2022", "Credit": "1810"},
    {"name": "LG 32-inch 8K Monitor", "type": "3", "Manufacturing Year": "2023", "Credit": "2000"},
    {"name": "Dell 24-inch Full HD Monitor", "type": "3", "Manufacturing Year": "2021", "Credit": "1765"},
    {"name": "Sony 55-inch OLED TV", "type": "3", "Manufacturing Year": "2022", "Credit": "1840"},
    {"name": "Samsung 65-inch QLED TV", "type": "3", "Manufacturing Year": "2023", "Credit": "1960"},
    {"name": "LG 49-inch UltraWide Monitor", "type": "3", "Manufacturing Year": "2022", "Credit": "1805"},
    {"name": "Toshiba 43-inch LED TV", "type": "3", "Manufacturing Year": "2020", "Credit": "1610"},
    {"name": "AOC 27-inch Curved Monitor", "type": "3", "Manufacturing Year": "2021", "Credit": "1735"},
    {"name": "Sony 75-inch 4K TV", "type": "3", "Manufacturing Year": "2022", "Credit": "1865"},
    {"name": "Samsung 32-inch 1080p Monitor", "type": "3", "Manufacturing Year": "2019", "Credit": "1555"},
    {"name": "LG 43-inch 4K TV", "type": "3", "Manufacturing Year": "2020", "Credit": "1610"},
    {"name": "Dell 34-inch Ultrawide Monitor", "type": "3", "Manufacturing Year": "2022", "Credit": "1785"},
    {"name": "Sony 85-inch 8K TV", "type": "3", "Manufacturing Year": "2023", "Credit": "1975"},
    {"name": "Samsung 55-inch QLED TV", "type": "3", "Manufacturing Year": "2021", "Credit": "1720"},
    {"name": "HP 27-inch 4K Monitor", "type": "3", "Manufacturing Year": "2022", "Credit": "1825"},
    {"name": "LG 65-inch OLED TV", "type": "3", "Manufacturing Year": "2021", "Credit": "1715"},
    {"name": "Dell 22-inch Full HD Monitor", "type": "3", "Manufacturing Year": "2020", "Credit": "1630"},
    {"name": "Sony 49-inch 4K TV", "type": "3", "Manufacturing Year": "2022", "Credit": "1850"},
    {"name": "Samsung 24-inch 1080p Monitor", "type": "3", "Manufacturing Year": "2019", "Credit": "1595"},
    {"name": "LG 55-inch 4K TV", "type": "3", "Manufacturing Year": "2020", "Credit": "1630"},
    {"name": "Dell 27-inch Full HD Monitor", "type": "3", "Manufacturing Year": "2021", "Credit": "1705"},
    {"name": "Sony 32-inch 720p TV", "type": "3", "Manufacturing Year": "2018", "Credit": "1480"},
    {"name": "Samsung 28-inch 4K Monitor", "type": "3", "Manufacturing Year": "2019", "Credit": "1575"},
    {"name": "LG 75-inch 8K TV", "type": "3", "Manufacturing Year": "2022", "Credit": "1960"},
    {"name": "Dell 23-inch Full HD Monitor", "type": "3", "Manufacturing Year": "2020", "Credit": "1655"},
    {"name": "Sony 65-inch OLED TV", "type": "3", "Manufacturing Year": "2021", "Credit": "1805"},
    {"name": "Samsung 22-inch 1080p Monitor", "type": "3", "Manufacturing Year": "2018", "Credit": "1495"},
    {"name": "LG 40-inch 4K TV", "type": "3", "Manufacturing Year": "2019", "Credit": "1610"},
    {"name": "Dell 32-inch 4K Monitor", "type": "3", "Manufacturing Year": "2021", "Credit": "1765"},
    {"name": "Sony 43-inch 4K TV", "type": "3", "Manufacturing Year": "2020", "Credit": "1735"},
    {"name": "Samsung 20-inch 720p Monitor", "type": "3", "Manufacturing Year": "2017", "Credit": "1445"},
    {"name": "LG 32-inch 1080p TV", "type": "3", "Manufacturing Year": "2018", "Credit": "1535"},
    {"name": "Dell 27-inch QHD Monitor", "type": "3", "Manufacturing Year": "2020", "Credit": "1735"},
    {"name": "Sony 55-inch 4K OLED TV", "type": "3", "Manufacturing Year": "2021", "Credit": "1785"},
    {"name": "Samsung 19-inch 720p Monitor", "type": "3", "Manufacturing Year": "2016", "Credit": "1395"},
    {"name": "LG 24-inch 1080p TV", "type": "3", "Manufacturing Year": "2017", "Credit": "1460"},
    {"name": "Dell 29-inch Ultrawide Monitor", "type": "3", "Manufacturing Year": "2020", "Credit": "1735"},
    {"name": "Sony 75-inch 8K OLED TV", "type": "3", "Manufacturing Year": "2022", "Credit": "1945"},
    {"name": "Samsung 17-inch 720p Monitor", "type": "3", "Manufacturing Year": "2015", "Credit": "1340"},
    {"name": "LG 28-inch 4K TV", "type": "3", "Manufacturing Year": "2016", "Credit": "1415"},
    {"name": "Dell 31.5-inch 4K Monitor", "type": "3", "Manufacturing Year": "2019", "Credit": "1575"},
    {"name": "Sony 85-inch 4K TV", "type": "3", "Manufacturing Year": "2020", "Credit": "1750"},
    {"name": "Samsung 15-inch 720p Monitor", "type": "3", "Manufacturing Year": "2014", "Credit": "1320"},

    {"name": "Samsung Refrigerator", "type": "4", "Manufacturing Year": "2022", "Credit": "4850"},
    {"name": "Whirlpool Washing Machine", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "LG Air Conditioner", "type": "4", "Manufacturing Year": "2021", "Credit": "4650"},
    {"name": "GE Dishwasher", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "KitchenAid Oven", "type": "4", "Manufacturing Year": "2020", "Credit": "4500"},
    {"name": "Panasonic Microwave", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Sony TV", "type": "4", "Manufacturing Year": "2022", "Credit": "4700"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Samsung Refrigerator", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Whirlpool Washing Machine", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "LG Air Conditioner", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "GE Dishwasher", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "KitchenAid Oven", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Panasonic Microwave", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Sony TV", "type": "4", "Manufacturing Year": "2022", "Credit": "4700"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2022", "Credit": "4700"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2015", "Credit": "3850"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2015", "Credit": "3850"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2015", "Credit": "3850"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2015", "Credit": "3850"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2015", "Credit": "3850"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2015", "Credit": "3850"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2020", "Credit": "4450"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2018", "Credit": "4250"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "GE Microwave", "type": "4", "Manufacturing Year": "2021", "Credit": "4600"},
    {"name": "KitchenAid TV", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Bosch Dryer", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},
    {"name": "Hitachi Refrigerator", "type": "4", "Manufacturing Year": "2022", "Credit": "4750"},
    {"name": "LG Washing Machine", "type": "4", "Manufacturing Year": "2016", "Credit": "3950"},
    {"name": "Samsung Air Conditioner", "type": "4", "Manufacturing Year": "2017", "Credit": "4150"},
    {"name": "Whirlpool Dishwasher", "type": "4", "Manufacturing Year": "2019", "Credit": "4300"},
    {"name": "Panasonic Oven", "type": "4", "Manufacturing Year": "2023", "Credit": "5000"},

]

Creditlist = pd.DataFrame(Device)
print(Creditlist)